sequenceDiagram
    participant M as Multi-Party Transaction
    participant C as Cloak Tx pools
    participant E as EVM execution
    participant L as Ledger

    M ->> M: Verify Signatrue
    M ->>+ C: Check Transaction <br> has already exist
    C ->>+ L: By hash of target Transaction
    L --)- C: Information of target Transaction
    alt Check the legitimacy of Multi-Party
        Note over C,E: PASS
    end
    C ->> C: Accept Multi-Party input data
    alt <br>Check whether the inputs paramters <br> has already complete
        Note over C,E: PASS
    else Not complete
        Note over C,E: Wait for other Multi-Party
    end
    C ->>+ E: execution Transaction
    E --)- C: result in EVM
    C ->> L: save to Ledger
    deactivate C
