sequenceDiagram
    participant M as Multi-Party Transaction
    participant C as Cloak Tx pools
    participant E as EVM execution
    participant L as Ledger

    M ->> M: Verify signatrue
    M ->>+ C: Check transaction <br> whether exist
    C ->>+ L: Check by the hash of target transaction
    L --)- C: Return information of target transaction
    alt Check the legitimacy of Multi-Party
        Note over C,E: PASS
    end
    C ->> C: Accept Multi-Party's input data
    alt Check the completeness of inputs
        Note over C,E: PASS
    else Not complete
        Note over C,E: Wait for other Multi-Party
    end
    C ->>+ E: Execute transaction
    E --)- C: Return result in EVM
    C ->> L: Save it to the ledger
    deactivate C
