sequenceDiagram
    autonumber
    participant P as Privacy Transaction
    participant PI as Privacy Interpret
    participant L as Ledger
    activate P
    P ->>+ P: Verify Signatrue
    P ->> + PI: Check paramter type 
    PI ->>- L: Check whether the policy exists
    activate L
    alt Privacy policy already exist
        L --) P: Check binding relationship between policy and user
        alt Has already binding
            Note over P, L: THROW ERR
        end
    else Not exist
        P ->> L: Save privacy policy to the Ledger
    end
    deactivate L
    P ->> P: Set binding <br> relationship  between <br> privacy policy and <br> confidential smart contract
    deactivate P