
sequenceDiagram
    participant M as Multi-Party Transaction
    participant C as Cloak Tx pools
    participant E as EVM execution
    participant K as Key Managerment
    participant P as Privacy Policy
    participant B as BlockChain
    M ->> M: Verify Signatrue
    M ->>+ C: Check Transaction <br> whether exist
    alt Check privacy policy whether exist
        C ->>+ P: Send the name and address of target function
        P --)- C: Return privacy policy modules
    else Not exist
        Note over C,P: THROW ERROR: Privacy policy not exist
    end
    C ->> B: Send synchronized data state of contract
    B --)+ K: Return encrypted data state
    K --)- C: Put data state
    alt Check transaction type
        alt Execute confidential transaction   
            C ->>+ E: Execute transaction
            E --)- C: Return result in EVM
        else Multi-Party Transaction
            Note over C,E: Wait for other MPT until meet the demand
        end
    end
    deactivate C
